### ISSUE TITLE
Ctrl+ArrowKey then Insert/num0 results in a panic.

### ISSUE THREAD

**Issue by ca1ek** [ticki/termion#47]
1. Run example keys
2. Press Ctrl+UpArrow, then press Insert
3. PANIC!!!!!

stacktrace(the example runs in raw mode so it's broken, but still readable, I think):

```
q to exit. Type stuff, use alt, and so on.thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', ../src/libcore/result.rs:788
   stack backtrace:
                      1:     0x55efe7d8fb0f - std::sys::backtrace::tracing::imp::write::h29f5fdb9fc0a7395
                                                                                                            2:     0x55efe7d9257b - std::panicking::default_hook::_{{closure}}::h2cc84f0378700526
                  3:     0x55efe7d91a35 - std::panicking::default_hook::hbbe7fa36a995aca0
                                                                                            4:     0x55efe7d91fee - std::panicking::rust_panic_with_hook::h105c3d42fcd2fb5e
                                                                                                                                                                              5:     0x55efe7d91e51 - std::panicking::begin_panic::hbf62ea4a5ff3f9de
                                                                     6:     0x55efe7d91d7a - std::panicking::begin_panic_fmt::h20f5943904e5791d
                                                                                                                                                  7:     0x55efe7d91cee - rust_begin_unwind
            8:     0x55efe7dc817f - core::panicking::panic_fmt::h19323e466869c656
                                                                                    9:     0x55efe7d80e3a - core::result::unwrap_failed::h5b2d2716cda99262
                                                                                                                                                                                  at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/macros.rs:29
                                                                                                   10:     0x55efe7d7fdff - _<core..result..Result<T, E>>::unwrap::hf71512fe510162b6
                          at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/result.rs:726
                                                                                                                              11:     0x55efe7d84a2c - termion::event::parse_event::haa61aaa8183b09ef
                                           at /home/dawid/Programming/termion/src/event.rs:215
                                                                                                12:     0x55efe7d85a74 - _<termion..input..Events<I> as core..iter..iterator..Iterator>::next::hc7597416b090804d
                                                      at /home/dawid/Programming/termion/src/input.rs:40
                                                                                                          13:     0x55efe7d85645 - _<termion..input..Keys<I> as core..iter..iterator..Iterator>::next::hc620f9b112985281
                                                              at /home/dawid/Programming/termion/src/input.rs:19
                                                                                                                  14:     0x55efe7d865ae - keys::main::hbf0ba45568932cf1
                                                                                                                                                                                                at /home/dawid/Programming/termion/examples/keys.rs:18
                                                                      15:     0x55efe7d91cb8 - std::panicking::try::call::h5df3ac2979db3c90
                                                                                                                                             16:     0x55efe7d9a116 - __rust_maybe_catch_panic
              17:     0x55efe7d910de - std::rt::lang_start::hfe9ab243c60ffb9b
                                                                               18:     0x55efe7d871e3 - main
                                                                                                              19:     0x7f0aa2e1a82f - __libc_start_main
                                                                                                                                                          20:     0x55efe7d7c918 - _start
         21:                0x0 - <unknown>
                                           error: Process didn't exit successfully: `target/debug/examples/keys` (exit code: 101)
```

**Comment by ticki** [comment]
Fixed:

```
q to exit. Type stuff, use alt, and so on.thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', ../src/libcore/result.rs:788
stack backtrace:
1:     0x55efe7d8fb0f - std::sys::backtrace::tracing::imp::write::h29f5fdb9fc0a7395
2:     0x55efe7d9257b - std::panicking::default_hook::_{{closure}}::h2cc84f0378700526
3:     0x55efe7d91a35 - std::panicking::default_hook::hbbe7fa36a995aca0
4:     0x55efe7d91fee - std::panicking::rust_panic_with_hook::h105c3d42fcd2fb5e
5:     0x55efe7d91e51 - std::panicking::begin_panic::hbf62ea4a5ff3f9de
6:     0x55efe7d91d7a - std::panicking::begin_panic_fmt::h20f5943904e5791d
7:     0x55efe7d91cee - rust_begin_unwind
8:     0x55efe7dc817f - core::panicking::panic_fmt::h19323e466869c656
9:     0x55efe7d80e3a - core::result::unwrap_failed::h5b2d2716cda99262
at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/macros.rs:29
10:     0x55efe7d7fdff - _<core..result..Result<T, E>>::unwrap::hf71512fe510162b6
at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/result.rs:726
11:     0x55efe7d84a2c - termion::event::parse_event::haa61aaa8183b09ef
at /home/dawid/Programming/termion/src/event.rs:215
12:     0x55efe7d85a74 - _<termion..input..Events<I> as core..iter..iterator..Iterator>::next::hc7597416b090804d
at /home/dawid/Programming/termion/src/input.rs:40
13:     0x55efe7d85645 - _<termion..input..Keys<I> as core..iter..iterator..Iterator>::next::hc620f9b112985281
at /home/dawid/Programming/termion/src/input.rs:19
14:     0x55efe7d865ae - keys::main::hbf0ba45568932cf1
    at /home/dawid/Programming/termion/examples/keys.rs:18
15:     0x55efe7d91cb8 - std::panicking::try::call::h5df3ac2979db3c90
16:     0x55efe7d9a116 - __rust_maybe_catch_panic
17:     0x55efe7d910de - std::rt::lang_start::hfe9ab243c60ffb9b
18:     0x55efe7d871e3 - main
19:     0x7f0aa2e1a82f - __libc_start_main
20:     0x55efe7d7c918 - _start
21:                0x0 - <unknown>
error: Process didn't exit successfully: `target/debug/examples/keys` (exit code: 101)
```

**Comment by gyscos** [comment]
I can reproduce it.
Bytes sent:
```
'\u{1b}'	'['	'1'	';'	'5'	'D'
'\u{1b}'	'['	'2'	'~'
```

**Comment by gyscos** [comment]
According to wikipedia,
> The final byte is technically any character in the range 64–126 (hex 0x40–0x7E, ASCII @ to ~), and may be modified with leading intermediate bytes in the range 32 to 47 (hex 0x20–0x2F, ASCII space to /).

So even if not all CSI sequences are parsed, the range 64-126 can still be used to detect the end of the sequence.
