### ISSUE TITLE
Crash on "Shift+Del"

### ISSUE THREAD

**Issue by gyscos** [ticki/termion#62]
Using termion 1.1.1 and this test program:

``` rust
extern crate termion;
fn main() {
    use termion::input::TermRead;
    let mut keys = std::io::stdin().keys();
    loop {
        if let Some(Ok(termion::event::Key::Char('q'))) = keys.next() {
            break;
        }
    }
}
```

Entering `Shift+Del` `Enter` results in the following crash:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', ../src/libcore/result.rs:799
stack backtrace:
   1:     0x55a9aef416ff - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2
   2:     0x55a9aef4434d - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd
   3:     0x55a9aef43702 - std::panicking::default_hook::h852b4223c1c00c59
   4:     0x55a9aef43c48 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
   5:     0x55a9aef43ae2 - std::panicking::begin_panic::hf6c488cee66e7f17
   6:     0x55a9aef43a20 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
   7:     0x55a9aef439a1 - rust_begin_unwind
   8:     0x55a9aef78f7f - core::panicking::panic_fmt::h9af671b78898cdba
   9:     0x55a9aef36d0c - core::result::unwrap_failed::h56469e47aa893530
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/macros.rs:29
  10:     0x55a9aef35ad3 - <core::result::Result<T, E>>::unwrap::hc5d8f1a2ba955958
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/result.rs:737
  11:     0x55a9aef3a078 - termion::event::parse_event::he508caeaec83cde7
                        at /home/gyscos/.cargo/registry/src/github.com-1ecc6299db9ec823/termion-1.1.1/src/event.rs:227
  12:     0x55a9aef3b514 - <termion::input::Events<I> as core::iter::iterator::Iterator>::next::h7422f5351027bba5
                        at /home/gyscos/.cargo/registry/src/github.com-1ecc6299db9ec823/termion-1.1.1/src/input.rs:40
  13:     0x55a9aef3b162 - <termion::input::Keys<I> as core::iter::iterator::Iterator>::next::h41ef409e002c8000
                        at /home/gyscos/.cargo/registry/src/github.com-1ecc6299db9ec823/termion-1.1.1/src/input.rs:19
  14:     0x55a9aef3ba1d - ttest::main::hce43c4c8af9629dc
                        at /home/gyscos/dev/ttest/src/main.rs:6
  15:     0x55a9aef4be16 - __rust_maybe_catch_panic
  16:     0x55a9aef42f81 - std::rt::lang_start::h14cbded5fe3cd915
  17:     0x55a9aef3bb63 - main
  18:     0x7f4e4831e290 - __libc_start_main
  19:     0x55a9aef33ae9 - _start
  20:                0x0 - <unknown>
```

**Comment by gyscos** [comment]
Bytes sent as input:
```
'\u{1b}'
'['
'3'
';'
'2'
'~'
'\n'
```

**Comment by ticki** [comment]
Interesting...
