### ISSUE TITLE
Panic on piped input in raw mode

### ISSUE THREAD

**Issue by aleksander** [ticki/termion#64]
termion 1.1.1

``` Rust
extern crate termion;
fn main() {
    use termion::input::TermRead;
    use termion::raw::IntoRawMode;
    let mut _stdout = std::io::stdout().into_raw_mode().unwrap();
    let mut stdin = termion::async_stdin().keys();
    loop {
        let s = stdin.next();
        if let Some(some) = s {
            println!("{:?}", some);
            if let Ok(termion::event::Key::Char('q')) = some {
                break;
            }
        }
    }
}
```
Running by 'echo "ABC" | app' causes panic:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("Unable to get Termios attribute.") }) }', ../src/libcore/result.rs:799
stack backtrace:
   1:     0x565013a5493f - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2
   2:     0x565013a5822d - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd
   3:     0x565013a57532 - std::panicking::default_hook::h852b4223c1c00c59
   4:     0x565013a57b28 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
   5:     0x565013a579c2 - std::panicking::begin_panic::hf6c488cee66e7f17
   6:     0x565013a57900 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
   7:     0x565013a57881 - rust_begin_unwind
   8:     0x565013a8ceef - core::panicking::panic_fmt::h9af671b78898cdba
   9:     0x565013a2e28e - core::result::unwrap_failed::h3ea0c9548cd89371
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/macros.rs:29
  10:     0x565013a299fe - <core::result::Result<T, E>>::unwrap::hdd81e7ca42639528
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/result.rs:737
  11:     0x565013a36cb7 - tt::main::heca67ea268605a0c
                        at /tmp/tt/src/main.rs:5
  12:     0x565013a5fcf6 - __rust_maybe_catch_panic
  13:     0x565013a56db1 - std::rt::lang_start::h14cbded5fe3cd915
  14:     0x565013a37373 - main
  15:     0x7f78bb896290 - __libc_start_main
  16:     0x565013a23969 - _start
  17:                0x0 - <unknown>
```
I believe this bug is somehow related to #63

**Comment by IGI-111** [comment]
So this is because there is some read from stdin needed to turn stdout into raw mode (namely by `termios::get_terminal_attr`).

Currently we assume that nothing is going on stdin/stdout when you turn them into raw mode. If something is on stdin before the terminal answer, it crashes because it can't read the answer to the termios request.

Question is: what is the correct behaviour here?

If we try and consume whatever is before the terminal answer, we risk hanging for as long as there is stuff on stdin, and it will all get ignored anyways.

Perhaps we could use a way to restore the terminal that doesn't require getting its whole state via stdin?
We could avoid the need for Termios by doing the initialization and restoration [Termbox-style](https://gist.github.com/IGI-111/93bb81a98bd7297d35a4a5f8c49f7440) sending just escape codes (kinda like `MouseTerminal` works actually).

**Comment by olivernn** [comment]
I've also run into this issue. Is there any workaround that I can use in my application?

**Comment by lotabout** [comment]
@olivernn I recently met this problem as well, and here is the workaround that I use:

```rust
    use std::fs::File;
    use std::os::unix::io::{FromRawFd, IntoRawFd};

    unsafe {
        //let old_stdin = File::from_raw_fd(libc::dup(libc::STDIN_FILENO));
        let tty = File::open("/dev/tty").unwrap();
        libc::dup2(tty.into_raw_fd(), libc::STDIN_FILENO);
    }
```

Put this code before `stdout().into_raw_mode()`.

The idea is to use `dup2` to redirect `/dev/tty` back to stdin.

**Comment by olivernn** [comment]
@lotabout thanks, that's working for me. Also first time I've had to use `unsafe`!
