### ISSUE TITLE
[cargo fuzz] TermRead

### ISSUE THREAD

**Issue by quininer** [ticki/termion#94]
I try using the `cargo-fuzz` to fuzz `termion::input::TermRead`, found some problems. https://github.com/quininer/fuzz-termion-termread

### called `Option::unwrap()` on a `None` value
payload (base64): `qw==` / `9Q==` / `qg==`

### stack-buffer-overflow
This should is false positive, see https://github.com/rust-lang/rust/issues/39882
playload (base64): `Kjc=`

**Comment by IGI-111** [comment]
Ok so this minimal example
```
extern crate termion;

use termion::input::TermRead;
use std::io::Cursor;

fn main() {
    let values = Cursor::new(vec![0xAB]);

    for c in values.keys() {
        println!("{:?}", c);
    }
}
```
gives us this full stack trace
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:323
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: <core::option::Option<T>>::unwrap
             at /checkout/src/libcore/macros.rs:21
   1: termion::event::parse_utf8_char
             at ./src/event.rs:317
   2: termion::event::parse_event
             at ./src/event.rs:135
   3: termion::input::parse_event
             at ./src/input.rs:86
   4: <termion::input::Events<R> as core::iter::iterator::Iterator>::next
             at ./src/input.rs:57
   5: <termion::input::Keys<R> as core::iter::iterator::Iterator>::next
             at ./src/input.rs:19
   6: keys::main
             at ./examples/keys.rs:9
```

Which seems to be caused by the fact that `parse_utf8_char()` makes the assumption that at least four bytes or one UTF-8 glyph are still to read in the input.

**Comment by quininer** [comment]
Now we have new fuzz result.

playload (base64): `G1s8`

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335
...
  11: termion::event::parse_csi
...
```
